### PR TITLE
feat: Included Norwegian translations for Vuetify

### PR DESCRIPTION
**Pull request by tft-abel**
I'd prefer making these changes on a global level here

### CODE REVIEW

**Comment by imable** [comment]
We should either remove all translation stuff from here, or still get this merged if you got errors that the `no` translations could not be found. That is a bug here with telling Vuetify to use `no`, but not actually including `no` @tfk-kaare.

**Review by tfk-kaare — COMMENTED** [review]
Yes, ok, this is a bit messy. 'nno' here and 'no' in specific app repos…

Somewhat unrelated; seeing that we/you have a custom 'nno' translation for vuetify stuff, this should be pushed upstream to the vuetify team.

Aaand, locale and language settings still belongs per app, imho. This package should not be 'one package to rule every app @ tfk-samf', but only concern itself with minimum common nominator for shared design systems and components.

If we are to have a component library, I think that should reside in a separate repo.

The more I write about this, the more it's clear that we should meet up and discuss the architecture of this and how to share stuff between projects …

**Comment by imable** [comment]
So were adding this one here? @tfk-kaare

**Comment by tfk-kaare** [comment]
Yes.. lets :-)

**Pull request merged**
